package com.chatmen.c_men.core.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF626200)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFe9e96d)
val LightOnPrimaryContainer = Color(0xFF1d1d00)
val LightSecondary = Color(0xFF616043)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFe6e4bf)
val LightOnSecondaryContainer = Color(0xFF1c1d06)
val LightTertiary = Color(0xFF3d6656)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFbfecd8)
val LightOnTertiaryContainer = Color(0xFF002116)
val LightError = Color(0xFFba1b1b)
val LightErrorContainer = Color(0xFFffdad4)
val LightOnError = Color(0xFFffffff)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFfffcf3)
val LightOnBackground = Color(0xFF1c1c16)
val LightSurface = Color(0xFFfffcf3)
val LightOnSurface = Color(0xFF1c1c16)
val LightSurfaceVariant = Color(0xFFe6e3d1)
val LightOnSurfaceVariant = Color(0xFF48473a)
val LightOutline = Color(0xFF797869)
val LightInverseOnSurface = Color(0xFFf4f0e8)
val LightInverseSurface = Color(0xFF31302b)

val DarkPrimary = Color(0xFFcccc54)
val DarkOnPrimary = Color(0xFF323200)
val DarkPrimaryContainer = Color(0xFF494900)
val DarkOnPrimaryContainer = Color(0xFFe9e96d)
val DarkSecondary = Color(0xFFcac8a5)
val DarkOnSecondary = Color(0xFF323218)
val DarkSecondaryContainer = Color(0xFF48482d)
val DarkOnSecondaryContainer = Color(0xFFe6e4bf)
val DarkTertiary = Color(0xFFa4d0bd)
val DarkOnTertiary = Color(0xFF0b372a)
val DarkTertiaryContainer = Color(0xFF254e40)
val DarkOnTertiaryContainer = Color(0xFFbfecd8)
val DarkError = Color(0xFFffb4a9)
val DarkErrorContainer = Color(0xFF930006)
val DarkOnError = Color(0xFF680003)
val DarkOnErrorContainer = Color(0xFFffdad4)
val DarkBackground = Color(0xFF1c1c16)
val DarkOnBackground = Color(0xFFe6e2da)
val DarkSurface = Color(0xFF1c1c16)
val DarkOnSurface = Color(0xFFe6e2da)
val DarkSurfaceVariant = Color(0xFF48473a)
val DarkOnSurfaceVariant = Color(0xFFcac7b6)
val DarkOutline = Color(0xFF939182)
val DarkInverseOnSurface = Color(0xFF1c1c16)
val DarkInverseSurface = Color(0xFFe6e2da)

val seed = Color(0xFFffff80)
val error = Color(0xFFba1b1b)